### ISSUE TITLE
Docker Container variant

### ISSUE THREAD

**Issue by kirinnee** [bloc97/Anime4K#12]
Seems like it requires OpenCL, but is it possible to run it in docker containers for easier deployment on servers or cross-platform development?

**Comment by stefnotch** [comment]
Where did you get the impression that it requires OpenCL?

**Comment by stefnotch** [comment]
Regarding Docker container, yes, it could theoretically run inside a Docker container, however, seeing as how it's a realtime algorithm that can easily run on any platform, most likely even the web, I'm not quite seeing the point of using Docker? Is there some use-case that I'm overlooking.

**Comment by kirinnee** [comment]
Impression was from when I ran everything within docker containers: (I hate to post logs but..)

`PS D:\same> docker run -v ${PWD}:/anime 4kanime ruby 4k.rb
Aug 15, 2019 11:44:14 AM com.aparapi.internal.opencl.OpenCLLoader <clinit>
SEVERE: Check your environment. Failed to load codegen native library  or possibly failed to locate opencl native library (opencl.dll/opencl.so). Ensure that OpenCL is in your PATH (windows) or in LD_LIBRARY_PATH (linux).
Exception in thread "main" javax.imageio.IIOException: Can't read input file!
        at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1308)
        at com.bloc97.anime4k.Main.main(Main.java:36)`

Host OS: Windows 10 Pro
Docker-image: openjdk:12-alpine

Perhaps its an alpine problem, I apologize for not checking if its an alpine problem before reporting, but I shall go do that tomorrow.

For starters, I prefer to not have Java installed on my computer.
Bu main reason being it makes if I were running servers that use the image to post-process image or anything of that sort, deployments will be much simpler than to write scripts to pre-install FFMPEG and JDK & curling the jar binary for every server spun up. Building it into a static image would make my other service dependent on it more readily.

**Comment by stefnotch** [comment]
Oh, you're right about the OpenCL usage. [Arapi](http://aparapi.com/) uses OpenCL to execute Java code on the GPU, which means that you would need a Docker image with OpenCL support.

**Comment by ddouglas87** [comment]
It works without OpenCL but complains while running.

On Docker Ubuntu `apt-get install -y ocl-icd-opencl-dev` removes the complaining, but I don't notice a speed difference.

**Comment by bloc97** [comment]
The algorithm is so simple that it is easy to be bounded by the memory speed. (Copying the image back and forth from the System Memory to the GPU Buffers) If your CPU is powerful enough (Recent CPUs with 8+ cores) it might even outperform GPUs since PCIe lanes are not as fast as the memory bus.

**Comment by kirinnee** [comment]
I have created a PR for basic Dockerfile, to build an ubuntu image that's portable.

I also have another one that packs FFMPEG into the image and added a script upscales videos by splitting and merging them (quite slow due to the restart of image kernel each time), should I add a PR for that too?
