### ISSUE TITLE
Lots of Exception when start NextGenAnimeEnhancer-1.0-SNAPSHOT.jar on windows 10

### ISSUE THREAD

**Issue by AaronFeng753** [bloc97/Anime4K#34]
Exception in thread "main" java.lang.NoClassDefFoundError: com/aparapi/Kernel
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:151)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:802)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:700)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:623)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at com.bloc97.anime4k.Main.<clinit>(Main.java:24)
Caused by: java.lang.ClassNotFoundException: com.aparapi.Kernel
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 10 more

**Comment by xpirad** [comment]
how did you solve the issue? @AaronFeng753

**Comment by AaronFeng753** [comment]
I didn't solve it, I just give it up. I download the package someone compiled for MAC and it runs perfectly on windows.
Link is here:
https://drive.google.com/file/d/1I1bTTtNtT2VhpXJMXawAS4ekYOSnRrKC/view?usp=sharing

**Comment by xpirad** [comment]
Oh, i see!
THX!
